### PR TITLE
Add support for dynamic screen mode selection

### PR DESCRIPTION
**Pull request by johnbatty**
The long-awaited implementation of #42!

Main changes:
- New API function: ```mode(width, height [, aspect_ratio])```
  - width and height are in pixels
  - aspect ratio is an optional floating point value defining the shape of the viewport.  1.0 is square, 2.0 is twice as wide as it is high.  So you can now write cinemascope games :-)
- Use runtime allocated Vecs rather than fixed-size Arrays for frame buffer and rendering texture
- Add width, height and aspect ratio fields to Screen, and use these instead of ```SCREEN_WIDTH/SCREEN_HEIGHT``` constants.  ```SCREEN_WIDTH/SCREEN_HEIGHT``` still exist, and define the initial screen size
- New example: mode/mode.py (based on font example).  Use arrows to change modes and fonts.
- New ```cls()``` implementation
- Changed code to ```lock().unwrap()``` screen at high level, then pass ```&mut gfx::Screen``` to functions rather than ```Arc<Mutex<gfx::Screen>>```.  Removes a load of ```lock().unwrap()```s in the lower level functions.
- Miscellaneous cleanups

It's a pretty big change, so there is a chance I may have broken some things.  But have tested as much as I can.
[One thing I haven't tested yet is the Lua interface.  I've added code, but not yet tested]

I retested performance and it is comparable with the fixed resolution version.

Enjoy!

### CODE REVIEW

**Comment by hallucino** [comment]
Awesome changements !!

**Comment by hallucino** [comment]
I tried the demo and other games it seems to work.

The demo is really great and the rendering is amazing !

**Comment by hallucino** [comment]
Do you think it is interesting to move to sdl2 0.30 ?

**Comment by hallucino** [comment]
@johnbatty do you think it is interesting ?

**Comment by johnbatty** [comment]
I just took a look.  I can't see any big benefit, other than keeping up with the latest version - no users of PX8 would notice the difference!  So I think you should probably open an issue for it, but that it is better to spend time on new features for now.

**Comment by hallucino** [comment]
I saw that the latest version of SDL is breaking the rendering, could you take a look ?

**Comment by hallucino** [comment]
@johnbatty what is your point on that ?

**Comment by johnbatty** [comment]
I assume you are talking about the latest Rust sdl-0.30?
Yes, it does have quite a few breaking changes.
I'll take a look and see if I can get it working.

**Comment by hallucino** [comment]
@johnbatty yeah it can be interesting to synchronize with this version !

**Pull request merged**
