### PR TITLE
Display game with correct aspect ratio for all window shapes

### PR DESCRIPTION
**Pull request by johnbatty**
It looks so much better when the pixels are square and the game isn't stretched :-)
I added the concept of a 'viewport' within the window, which is the area where the game is displayed.  

The window now has margins on the left/right or top/bottom to keep the viewport square and centralised within the window.

I implemented the code so it should also work if you build non-standard non-square game display sizes.

### CODE REVIEW

**Comment by hallucino** [comment]
Thank you !! Awesome :)

**Comment by hallucino** [comment]
@johnbatty Do you want to help me with a GFX renderer ? :)

**Comment by hallucino** [comment]
s/GFX/gfx-rs ?

**Comment by johnbatty** [comment]
Doh - I just realised that I need to adjust the reported mouse position to take account of the padding/scaling.  I'll make a fix for that, and do a little example mouse position test app.  Should be able to send you an update later today.

**Comment by johnbatty** [comment]
Yes, I'd be happy to help with a gfx-rs renderer.  I hadn't come across it before, but like the look of it.  I've got low-level graphics experience, and I've been looking for a little project to gain more Rust experience :-)

Other things I'm interested in doing.  Basically adding more PICO-8 features :-) But also with the option of a better font in the test editor to help with Python programming (where you really need lower case).
- add PICO-8 font / text output
- add higher res font (TRS-80, BBC computer or similar) for use in 256x256 editor
- add text editor
- add console
- add sound editor

Is there any particular reason why your didn't use the PICO-8 font in the current version?

**Comment by hallucino** [comment]
Great !!

Yeah all ideas are welcome !

For the font, the idea is to have the support of multiple fonts, so well any font could be fine and specially to fix the current one: https://github.com/Gigoteur/PX8/issues/24

For the sound editor yes too, but I need to add the sound in the first place :) https://github.com/Gigoteur/PX8/issues/5

For the text/console editors, it was not in my mind originally but it could be a real plus.

**Comment by hallucino** [comment]
I added you as a collaborators so you could take the bug you wish etc

**Comment by johnbatty** [comment]
Thanks!

**Pull request merged**
